image: docker:latest

services:
  - docker:dind

stages:
  - build
#  - test
#  - deploy
#  - clean

variables:
  IMAGE_BASE_NAME: andyandy/android
  IMAGE_NAME_TAG: $IMAGE_BASE_NAME:$CI_BUILD_REF
  IMAGE_NAME_LATEST_TAG: $IMAGE_BASE_NAME:latest
  DOCKER_REPOSITORY_URL: https://index.docker.io/v1/
  DOCKER_REPOSITORY_HOSTNAME: docker.io

# before_script:
#  - docker info
  
build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $IMAGE_NAME_TAG .
    - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD $DOCKER_REPOSITORY_URL
    - docker info
    - cat ~/.docker/config.json
    - docker tag $IMAGE_NAME_TAG $IMAGE_NAME_LATEST_TAG
    - docker tag $IMAGE_NAME_TAG $DOCKER_REPOSITORY_HOSTNAME/$IMAGE_NAME_TAG
    - docker push $DOCKER_REPOSITORY_HOSTNAME/$IMAGE_NAME_TAG
    - docker logout

#test:
#  script:
#    - docker run android-sdk /script/to/run/tests

#deploy:
#  stage: deploy
#  tags:
#    - docker
#  script:
#    - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD --email $DOCKER_HUB_EMAIL $DOCKER_REPOSITORY_URL
#    - docker tag $IMAGE_NAME_TAG $IMAGE_NAME_LATEST_TAG
#    - docker push $IMAGE_NAME_TAG
#    - docker logout

# clean_docker:
#  stage: clean
#  when: always
#  script:
#    - $COMPOSE stop
#    - $COMPOSE down
#    - $COMPOSE rm -f