image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

stages:
  - build
#  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t registry.example.com/group/project:latest .
    - docker build -t hub.docker.com/andyandy/android .

#test:
#  script:
#    - docker run android-sdk /script/to/run/tests

deploy:
  stage: deploy
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD hub.docker.com
    - docker push /andyandy/android:$CI_BUILD_REF_NAME
    - docker push /andyandy/android:latest
